[package]
name = "cw-tba"
version = { workspace = true }
authors = ["Kromsten <s@noreply.megarock.labs>"]
edition = { workspace = true }
repository = { workspace = true }
description = "Definition and types for Token-Bound Accounts"

[features]
default = []
multi = ["cw84/multi", "cw83/multi"]
ext_query = []
full_info = []
omniflix = ["dep:omniflix-std"]

[dependencies]
anybuf = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-ownable = { workspace = true }
cw83 = { workspace = true }
cw84 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }

saa-schema = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

saa-wasm = { workspace = true }

omniflix-std = { workspace = true, optional = true }
