[package]
name            = "cw-tba"
authors         = [ "Kromsten <s@noreply.megarock.labs>" ]
edition         = { workspace = true }
version         = { workspace = true }
repository      = { workspace = true }
description     = "Definition and types for Token-Bound Accounts"


[features]
default          = []
ext_query        = []
full_info        = []


[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars        = { workspace = true }
cw83            = { workspace = true }
cw82            = { workspace = true }
cw-ownable      = { workspace = true }
anybuf          = { workspace = true }

saa-schema      = { workspace = true }

#saa-schema          = { version = "0.24.5", features = ["cosmwasm", "session"], path = "../../../contract-auth/packages/schema" }
cw-auths            = { workspace = true }
