[package]
name            = "cw-tba"
authors         = [ "Kromsten <s@noreply.megarock.labs>" ]
edition         = { workspace = true }
version         = { workspace = true }
repository      = { workspace = true }
description     = "Definition and types for Token-Bound Accounts"

[features]
backtraces      = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std    = { workspace = true, features = ["staking", "stargate" ] }
cosmwasm-schema = { workspace = true }
schemars        = { workspace = true }
cw721           = { workspace = true }
