chain_cfg: 
  denom: "ustars"
  prefix: "stars"
  chain_id: "testing"
  rpc_endpoint: "http://localhost:26657"
  grpc_endpoint: "http://localhost:9090"
  gas_price: 0.1
  gas_adjustment: 1.5
  derivation_path: "m/44'/118'/0'/0/0"

contract_deploy_info:
  cw721_base:
    code_id: 4
  cw82_tba_base:
    code_id: 3
  cw83_tba_registry:
    code_id: 2
  cw82_tba_credentials:
    code_id: 1