chain_cfg: 
  denom: "aarch"
  prefix: "archway"
  chain_id: "testing"
  rpc_endpoint: "http://localhost:26657"
  grpc_endpoint: "http://localhost:9090"
  gas_price: 900000000000
  gas_adjustment: 1.8
  derivation_path: "m/44'/118'/0'/0/0"

contract_deploy_info:
  cw83_base:
    code_id: 4
  cw82_base:
    code_id: 3
  cw721_base:
    code_id: 2
  cw82_credentials: 
    code_id: 5