[workspace]
members = [
    "contracts/*",
    "packages/*",
    "e2e"
]

resolver = "2"

[workspace.package]
version    = "0.8.1"
edition    = "2021"
repository = ""



[workspace.dependencies]
cosmwasm-std         = { version = "2.1.4",  features = ["staking",  "cosmwasm_2_1" ] }
cosmwasm-schema      = "2.1.4"
cw-storage-plus      = "2.0.0"

serde                = { version = "1.0.214", features = ["derive"] }
anybuf               = { version = "0.5.0" }

semver                  = "1.0.23"
schemars                = "0.8.21"
thiserror               = "2.0.3"

cw-ownable              = "2.1.0"
cw-utils                = "2.0.0"
cw1                     = "2.0.0"
cw2                     = "2.0.0"
cw81                    = "1.1.0 "
cw82                    = "1.1.0"
cw83                    = "1.1.0"
cw22                    = "0.4.0"

cw82-tba-base           = { path = "contracts/cw82-tba-base", features = ["library"] }
cw82-tba-credentials    = { path = "contracts/cw82-tba-credentials", features = ["library"] }
cw83-tba-registry       = { path = "contracts/cw83-tba-registry", features = ["library"] }
cw-tba                  = { path = "packages/cw-tba"     }

saa                     = { version = "0.18.7", package = "smart-account-auth", features = ["cosmwasm_2_1"] }


[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
debug            = false
debug-assertions = false
opt-level        = 3