[workspace]
members = [
    "contracts/*",
    "packages/*",
    "e2e"
]

resolver = "2"

[workspace.package]
version    = "0.3.0"
edition    = "2021"
repository = ""



[workspace.dependencies]
cosmwasm-std         = { version = "1.5.5",  features = ["iterator", "staking", "ibc3", "iterator", "cosmwasm_1_4" ] }
cosmwasm-schema      = "1.5.5"
cw-storage-plus      = "0.16.0"

k256                 = { version = "0.13.1", default-features = false, features = ["ecdsa"] }
sha2                 = { version = "0.10.8", default-features = false }

semver                  = "1.0.23"
schemars                = "0.8.21"
thiserror               = "1.0.61"

cw-ownable              = "0.5.1"
cw-utils                = "1.0.3"
cw1                     = "1.1.2"
cw2                     = "1.1.2"

saa                     = { git = "https://github.com/MegaRockLabs/smart-account-auth", package = "smart-account-auth", features = ["cosmwasm"], version = "0.9.4"}
cw81                    = { git = "https://github.com/megarocklabs/cw-extra", package = "cw81" }
cw82                    = { git = "https://github.com/megarocklabs/cw-extra", package = "cw82" }
cw83                    = { git = "https://github.com/megarocklabs/cw-extra", package = "cw83" }
cw22                    = { git = "https://github.com/aura-nw/cw-plus",       package = "cw22" }


cw-tba                  = { path = "packages/cw-tba"     }
cw82-base               = { path = "contracts/cw82-base", features = ["library"] }
cw82-credentials        = { path = "contracts/cw82-credentials", features = ["library"] }
cw83-base               = { path = "contracts/cw83-base", features = ["library"] }

cw721-base              = { version = "0.18.0",  features = ["library"] }
cw721                   = "0.18.0"

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
debug            = false
debug-assertions = false
opt-level        = 3
