[workspace]
members = [
    "contracts/*",
    "packages/*",
    "e2e"
]

resolver = "2"

[workspace.package]
version    = "0.9.0"
edition    = "2021"
repository = ""



[workspace.dependencies]
cosmwasm-std         = { version = "1.5.8", features = ["staking", "stargate" ] }
cosmwasm-schema      = "1.5.8"
cw-storage-plus      = "1.2.0"

serde                = { version = "1.0.214", features = ["derive"] }
anybuf               = { version = "0.5.0" }

semver                  = "1.0.23"
schemars                = "0.8.21"
thiserror               = "2.0.4"

cw-ownable              = "0.5.1"
cw-utils                = "1.0.3"
cw1                     = "1.1.2"
cw2                     = "1.1.2"

cw22                    = { version = "1.5.9" }
cw81                    = { version = "1.3.0" }
cw82                    = { version = "1.3.0" }
cw83                    = { version = "1.3.0" }
saa                     = { version = "0.22.0", package = "smart-account-auth", features = ["cosmwasm"]}


cw-tba                  = { path = "packages/cw-tba" }
cw82-tba-base           = { path = "contracts/cw82-tba-base", features = ["library"] }
cw82-tba-credentials    = { path = "contracts/cw82-tba-credentials", features = ["library"] }
cw83-tba-registry       = { path = "contracts/cw83-tba-registry", features = ["library"] }

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
debug            = false
debug-assertions = false
opt-level        = 3