[workspace]
members = [
    "contracts/*",
    "packages/*",
    "e2e"
]

resolver = "2"

[workspace.package]
version    = "0.8.1"
edition    = "2021"
repository = ""



[workspace.dependencies]
cosmwasm-std         = { version = "2.1.4", default-features = false,  features = ["staking", "std" ] }

cosmwasm-schema      = "2.1.4"
cw-storage-plus      = "2.0.0"

serde                = { version = "1.0.214", features = ["derive"] }
anybuf               = { version = "0.5.0" }

semver                  = "1.0.23"
schemars                = "0.8.21"
thiserror               = "2.0.4"

cw-ownable              = "2.1.0"
cw-utils                = "2.0.0"
cw1                     = "2.0.0"
cw2                     = "2.0.0"

cw22                    = { version = "0.5.0", default-features = false, features = [] }
cw81                    = { version = "1.2.6", default-features = false, features = [] }
cw82                    = { version = "1.2.6", default-features = false, features = [] }
cw83                    = { version = "1.2.6", default-features = false, features = [] }

saa                     = { version = "0.18.12", package = "smart-account-auth", features = ["cosmwasm"]}


cw-tba                  = { path = "packages/cw-tba" }
cw82-tba-base           = { path = "contracts/cw82-tba-base", features = ["library"] }
cw82-tba-credentials    = { path = "contracts/cw82-tba-credentials", features = ["library"] }
cw83-tba-registry       = { path = "contracts/cw83-tba-registry", features = ["library"] }

[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
debug            = false
debug-assertions = false
opt-level        = 3