[workspace]
members = [
    "contracts/*",
    "packages/*",
    "e2e"
]

resolver = "2"

[workspace.package]
version    = "0.6.0"
edition    = "2021"
repository = ""



[workspace.dependencies]
cosmwasm-std         = { version = "1.5.8",  features = ["staking", "ibc3", "iterator", "cosmwasm_1_4" ] }
cosmwasm-schema      = "1.5.5"
cw-storage-plus      = "0.16.0"

serde                = { version = "1.0.204", features = ["derive"] }
sha2                 = { version = "0.10.8", default-features = false }
anybuf               = { version = "0.5.0" }

semver                  = "1.0.23"
schemars                = "0.8.21"
thiserror               = "1.0.61"

cw-ownable              = "0.5.1"
cw-utils                = "1.0.3"
cw1                     = "1.1.2"
cw2                     = "1.1.2"
cw81                    = "1.1.0 "
cw82                    = "1.1.0"
cw83                    = "1.1.0"
cw22                    = "0.2.0"
cw721                   = "0.18.0"
cw721-base              = { version = "0.18.0",  features = ["library"] }

cw82-base               = { path = "contracts/cw82-base", features = ["library"] }
cw82-credentials        = { path = "contracts/cw82-credentials", features = ["library"] }
cw83-base               = { path = "contracts/cw83-base", features = ["library"] }
cw-tba                  = { path = "packages/cw-tba"     }

saa                     = { package = "smart-account-auth", features = ["cosmwasm"], version = "0.11.3" }


[profile.release]
rpath            = false
lto              = true
overflow-checks  = true
debug            = false
debug-assertions = false
opt-level        = 3
