[package]
name = "cw82-base"
version     = { workspace = true }
edition     = { workspace = true }
repository  = { workspace = true }
authors = [ "Kromsten <s@noreply.megarock.labs>" ]
description = "Token Bound Account Base"

exclude = [
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
semver          = { workspace = true }
thiserror       = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
cw-ownable      = { workspace = true }
cw-utils        = { workspace = true }
cw2             = { workspace = true }
cw22            = { workspace = true }
cw82            = { workspace = true }
cw83            = { workspace = true }
cw721-base      = { workspace = true }
cw-tba          = { workspace = true }
sha2            = { version = "0.10.8", default-features = false }

